
server:
  port: 8081
  servlet:
    context-path: /myApp
spring:
  profiles:
    active: dev
---
server:
  port: 8082
spring:
  profiles: dev
  datasource:
     url: jdbc:mysql://123.207.252.249:3306/shiro?serverTimezone=Hongkong&amp;useUnicode=true&amp;characterEncoding=utf8&amp;useSSL=false
     username: root
     password: mch1021
mybatis:
   mapper-locations: classpath:mybatis/mapper/*.xml
   config-location: classpath:mybatis/mybatis-config.xml
   type-aliases-package: com.mch.system.entity
---
server:
  port: 8084
spring:
  profiles: prod
  thymeleaf:
    cache: false
logging:
  level: trace
  path: /spring/log


